# Generated by Django 5.2.12 on 2026-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_logatividade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAtividade',
        ),
    ]
